Added deprecation warning when using v2 API
lizardsystem/lizard-connector pull request #21
Opened 2020-12-11 13:28 UTC by daanvaningen

![Screenshot from 2020-12-11 11-51-29](https://user-images.githubusercontent.com/11943796/101908859-fd084480-3bbc-11eb-81bd-ddb7d9713017.png)

Added this deprecation warning

The default API for the lizard-connector is V3 so no need to shut the whole thing down just yet

2020-12-11 13:42 UTC, caspervdw requested changes

2020-12-11 13:42 UTC, caspervdw commented on lizard_connector/connector.py
> +            depracationWarning ="""
In python we camel case only for classes.

```suggestion
            deprecation_warning ="""
```

2020-12-11 13:42 UTC, caspervdw commented on lizard_connector/connector.py
> +\033[91m============================================================\033[0m
I wonder how this looks in a notebook?

I am used to using `warnings.warn(msg)`, and not using any formatting in the msg.

The problem with print statements is that they can't really be handled by outside libraries. With warnings, other people have some control over them.

2020-12-16 09:07 UTC, daanvaningen commented
Changed to FutureWarnings as the DeprecationWarnings are ignored by default. FutureWarnings are intended to inform end users about where Deprecation warnings are intended for developers. (See https://docs.python.org/3/library/warnings.html)

2020-12-16 09:33 UTC, merged