Added exceptions for Python 2: import urllib2 and urlparse
lizardsystem/lizard-connector pull request #4
Opened 2017-02-02 16:11 UTC by GeOdin

2017-02-03 08:41 UTC, RoelvandenBerg requested changes
Je hebt gedaan we we hadden besproken, maar ik zie nu dat mijn aanname dat python 2.7 en 3.x alleen qua organisatie op module niveau verschillen niet helemaal correct is. Zonder het uitgeprobeerd te hebben zie ik in ieder geval een ding wat volgens mij niet kan werken. Loop de code even langs voor elke methode die gebruikt wordt of die wel op de plek zit die we verwachten.

Daarnaast is het goed om standaard even de codewijziging uit te proberen. Heb je de library ook uitgetest? Ik zou in de directory waar je het hebt staan even python en python3 starten. Verbinding maken met staging `https://nxt.staging.lizard.net` en bijvoorbeeld het timeseries endpoint bevragen. Of de example code uitvoeren die in de readme staat. Als dat werkt is ie goed. De tests dekken dit deel waarschijnlijk niet helemaal af, ik heb urllib deels gemockt.

2017-02-03 08:41 UTC, RoelvandenBerg commented on lizard_connector/connector.py
> +    import urlparse as urllib_parse
ik zou kiezen voor:
```
try:
    from urllib import request
    from urllib import parse as urlparse
except ImportError:
    from urllib2 import request
    import urlparse
```

2017-02-03 08:41 UTC, RoelvandenBerg commented on lizard_connector/connector.py
> +        query = "?" + urllib_parse.urlencode(q)
urlencode zit niet in python 2.7 urlparse maar in urllib. Je zal urlencode dus los moeten importeren voor beide python versies.

2017-02-08 10:05 UTC, GeOdin commented
Tested new version for Python 2 and Python 3.
It works for the (new) examples.

2017-02-08 10:36 UTC, RoelvandenBerg commented on lizard_connector/connector.py
> +        return json.load(response)
volgens mij wil je dit doen?

```
content = resp.read().decode('UTF-8')
return json.loads(content)
```

2017-02-08 10:38 UTC, RoelvandenBerg commented on lizard_connector/connector.py
>          raise StopIteration
Dit is niet DRY

```
def next(self):
    return __next__()
```

2017-02-08 10:39 UTC, RoelvandenBerg commented on lizard_connector/connector.py
> +            super(Endpoint, self).__init__(**kwargs)
`super(Endpoint, self).__init__(**kwargs)` werkt ook in python3 dus je hebt geen try except nodig. Test maar even uit.

2017-02-08 10:41 UTC, RoelvandenBerg commented on lizard_connector/connector.py
>                  'data')
Past dit nu op een regel?

2017-02-08 10:41 UTC, RoelvandenBerg commented on lizard_connector/queries.py
urlparse vind ik mooier

2017-02-08 10:54 UTC, jackieleng commented
https://pypi.python.org/pypi/3to2
:smile:

2017-02-08 14:28 UTC, RoelvandenBerg approved these changes

2017-02-08 14:29 UTC, merged